name: variant_conda_environment
channels:
  - conda-forge
  - bioconda
dependencies:
  - star=2.5.* 
  - bwa=0.7.* 
  - fastqc=0.11.*
  - multiqc=1.6
  - bowtie2=2.4.*
  - lofreq=2.1.*
  - snpeff=5.0.*
  - gatk4=4.0.* 
  - cutadapt=3.0
  - samtools=1.11
  - nextflow=20.10.*
  - r-base=4.0.*
  - r-tidyverse=1.3.*
  - r-openxlsx=4.2.* 
  - r-vcfr=1.12.*
  - snpsift
